add GitHub Actions file
StLeoX/chatops pull request #15
Opened 2023-12-13 13:51 UTC by X1ahua

2023-12-14 04:53 UTC, gurth approved these changes

2023-12-14 15:22 UTC, StLeoX requested changes
基本是这样。
我希望 pytest 能生成 HTML 报告，并上传附件，这样方便浏览一点。
提示：
https://pypi.org/project/pytest-html/
https://github.com/actions/upload-artifact

2023-12-21 07:41 UTC, StLeoX approved these changes

2023-12-21 07:41 UTC, StLeoX commented on .github/workflows/test_ci.yml
> +
-> Unit Test

2023-12-21 07:41 UTC, merged